In [20]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from sklearn.preprocessing import LabelEncoder

In [21]:
# First Feature
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
# Second Feature
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

# Label or target varible
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [29]:
le = LabelEncoder()
weather_encoded = le.fit_transform(weather)
temp_encoded = le.fit_transform(temp)
play_encoded = le.fit_transform(play)

In [30]:
weather_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

In [31]:
weather_encoded = weather_encoded.reshape(weather_encoded.shape[0], -1)
temp_encoded = temp_encoded.reshape(temp_encoded.shape[0], -1)
play_encoded = play_encoded.reshape(play_encoded.shape[0], -1)

In [35]:
data = np.append(weather_encoded, temp_encoded, axis=1)
data = np.append(data, play_encoded, axis=1)

In [36]:
data

array([[2, 1, 0],
       [2, 1, 0],
       [0, 1, 1],
       [1, 2, 1],
       [1, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [2, 2, 0],
       [2, 0, 1],
       [1, 2, 1],
       [2, 2, 1],
       [0, 2, 1],
       [0, 1, 1],
       [1, 2, 0]], dtype=int64)

In [39]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features=[0])
data_tr = ohe.fit_transform(data).toarray()

d:\python35\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [45]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
model.fit(data[:, :2], data[:, 2])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=3, p=2,
           weights='uniform')

In [46]:
model.predict([[0, 2]])

array([1], dtype=int64)